<?php

// autoload_files.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'e047688227bba2aaf0f5b41ce3995e34' => $baseDir . '/includes/functions/init.php',
);
