<?php

// autoload_files.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    '838d2cd9e6e27ee02d7481a52b067d2b' => $vendorDir . '/gnnpls/wp-kit/bootstrap.php',
    '484f7a0bd33b9211fed5bca8f8fb9f5c' => $vendorDir . '/gnnpls/wp-self-test/bootstrap.php',
    'e047688227bba2aaf0f5b41ce3995e34' => $baseDir . '/includes/functions/init.php',
    '3d8cee44d66267b5f3478a6d3904910f' => $baseDir . '/includes/classes/class-encryption.php',
);
