<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitfb3118450273b47d95f6da240d881eb0
{
    public static $files = array (
        'e047688227bba2aaf0f5b41ce3995e34' => __DIR__ . '/../..' . '/includes/functions/init.php',
    );

    public static $prefixLengthsPsr4 = array (
        'E' => 
        array (
            'EWP\\' => 4,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'EWP\\' => 
        array (
            0 => __DIR__ . '/../..' . '/includes/classes',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
        'EWP\\Setup' => __DIR__ . '/../..' . '/includes/classes/Setup.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitfb3118450273b47d95f6da240d881eb0::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitfb3118450273b47d95f6da240d881eb0::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitfb3118450273b47d95f6da240d881eb0::$classMap;

        }, null, ClassLoader::class);
    }
}
