<?php return array(
    'root' => array(
        'name' => 'motivar/extend-wp',
        'pretty_version' => '1.5.0',
        'version' => '1.5.0.0',
        'reference' => null,
        'type' => 'wordpress-plugin',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'dev' => true,
    ),
    'versions' => array(
        'gnnpls/wp-kit' => array(
            'pretty_version' => 'v0.2.0',
            'version' => '0.2.0.0',
            'reference' => '7a7b245498c73f9faf1c97640b391eb2b6285d6d',
            'type' => 'library',
            'install_path' => __DIR__ . '/../gnnpls/wp-kit',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'gnnpls/wp-self-test' => array(
            'pretty_version' => 'v0.3.0',
            'version' => '0.3.0.0',
            'reference' => 'd795f090e3fddfb6621fc49afebb175b7f1b60bd',
            'type' => 'library',
            'install_path' => __DIR__ . '/../gnnpls/wp-self-test',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'motivar/extend-wp' => array(
            'pretty_version' => '1.5.0',
            'version' => '1.5.0.0',
            'reference' => null,
            'type' => 'wordpress-plugin',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
    ),
);
