stages:
  - mirror

mirror_repository_to_github:
  tags:
    - gitlab.motivar.io
  stage: mirror
  image: alpine/git
  only:
    - main # Adjust this as needed to your branch names
  script:
    - git config --global user.email "gnnpls.nikos@gmail.com" # Use your email
    - git config --global user.name "gnnpls" # Use your name
    - git clone --mirror $CI_PROJECT_URL
    - git remote add github $GITHUB_REPO_URL # Replace USERNAME/REPOSITORY with your GitHub repo path
    - git push --mirror "https://${GH_TOKEN}@github.com//Motivar/wp-extend.git"
