stages:
  - build


build:
  tags:
    - docker
  stage: build
  artifacts:
    expire_in: 1h
    paths:
      - build-$CI_COMMIT_REF_SLUG.tar.gz
  image: drud/ddev-webserver:v1.21.2 # PHP 8.0
  script:
    - composer install --no-dev --no-progress --prefer-dist --no-suggest --optimize-autoloader --ignore-platform-reqs
    - cd $CI_PROJECT_DIR
    - npm install && npm run production
    - composer update
    - cd $CI_PROJECT_DIR
    - find . -type d -name '.git' | xargs rm -rf
    - git init
    - git add -f web config vendor composer.json composer.lock wp-cli.yml .env
    - git -c user.name="Docker build" -c user.email="dev+wp@motivar.io" -c gc.auto=0 commit -qm "Build $CI_COMMIT_REF_SLUG"
    - git gc --aggressive
    - tar czf build-$CI_COMMIT_REF_SLUG.tar.gz web/ config/ vendor/ composer.json composer.lock wp-cli.yml .env .git/
