stages:
  - build
  - deploy


build:
  tags:
    - docker
  stage: build
  image: drud/ddev-webserver:v1.21.2 # PHP 8.0
  script:
    - composer install --no-dev --no-progress --prefer-dist --no-suggest --optimize-autoloader --ignore-platform-reqs
    - cd $CI_PROJECT_DIR
    - npm init -y
    - npm install --save-dev webpack webpack-cli @babel/core babel-loader @babel/preset-env @babel/preset-react @wordpress/scripts
    - npm run build
    - composer update -o
    - find . -type d -name '.git' | xargs rm -rf
    - tar -czf build-$CI_COMMIT_REF_SLUG.tar.gz .
  artifacts:
    expire_in: 1h
    paths:
      - build-$CI_COMMIT_REF_SLUG.tar.gz
    

deploy:
  stage: deploy
  tags:
    - docker
  script:
    - apk add curl
    - 'curl --header "Job-Token: $CI_JOB_TOKEN" --data tag=<tag> "${CI_API_V4_URL}/projects/$CI_PROJECT_ID/packages/composer"'
  environment: production