stages:
  - mirror

mirror_repository_to_github:
  stage: mirror
  tags:
    - gitlab.motivar.io
  image: alpine/git
  only:
    - main
  script:
    # Optional: Set the git user name and email.
    - git -v
  # Optional: Clean up by removing the temporary remote to avoid conflicts in future runs.
  after_script:
    - git remote remove github-mirror
