stages:
  - build
  
build_assets:
  stage: build
  image: node:latest
  tags:
    - docker
  script:
    - cd wp-extend
    - npm install
    - npm run build
  artifacts:
    paths:
      - wp-extend/build/
