stages:
  - preparation
  - code_quality
  - build
  - package
  - release

install_dependencies:
  stage: preparation
  tags:
    - docker
  script:
    - npm install
    - composer install --no-scripts

code_quality:
  stage: code_quality
  tags:
    - docker
  script:
    - ./vendor/bin/phpcs
    - npm run lint

build:
  stage: build
  tags:
    - docker
  script:
    - npm run build

package:
  stage: package
  tags:
    - docker
  script:
    - composer install --no-dev --no-scripts
    - zip -r my-plugin.zip .
  artifacts:
    paths:
      - my-plugin.zip


release:
  stage: release
  tags:
    - docker
  only:
    - main
  script:
    - 'VERSION=$(date +"%Y%m%d%H%M%S")'
    - 'git tag $VERSION'
    - 'git push origin $VERSION'