stages:
  - lint
  - build

lint_php:
  stage: lint
  image: php:7.4-cli
  script:
    - apt-get update && apt-get install -y php-xml
    - curl -sS https://getcomposer.org/installer | php
    - php composer.phar install
    - ./vendor/bin/phpcs --standard=WordPress --extensions=php,js ./your-plugin-directory/

build_assets:
  stage: build
  image: node:latest
  script:
    - cd wp-extend
    - npm install
    - npm run build
  artifacts:
    paths:
      - wp-extend/build/
