stages:
  - update_wiki

update_wiki:
  stage: update_wiki
  image: debian:latest
  tags:
    - docker
  script:
    # Install necessary tools
    - apt-get update && apt-get install -y git openssh-client bash

    # Start SSH agent
    - eval $(ssh-agent -s)
    - echo "$GITLAB_UPDATE_SSH_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - ssh-keyscan gitlab.motivar.io >> ~/.ssh/known_hosts

    # Clone the GitLab Wiki repository
    - git clone git@gitlab.motivar.io:plugins/extend-wp/wp-extend.wiki.git

    # Ensure the wiki directory exists
    - if [ ! -d "wp-extend.wiki" ]; then
        echo "Wiki directory does not exist. Exiting.";
        exit 1;
      fi

    # Remove existing wiki files to avoid duplication
    - rm -rf wp-extend.wiki/*

    # Find and process README.md files in the parent plugin folder
    - |
      files=$(find .. -type f -name "README.md")
      if [ -z "$files" ]; then
        echo "No README.md files found in the parent folder. Exiting."
        exit 0
      fi
      for file in $files; do
        echo "Processing file: $file"
        header=$(grep -m 1 "^# " "$file" | sed 's/^# //')
        filename=$(echo "$header" | tr ' ' '_' | tr '[:upper:]' '[:lower:]').md
        echo "Copying $file to ./wp-extend.wiki/$filename"
        cp "$file" "./wp-extend.wiki/$filename"
      done

    # Navigate to the wiki directory and push changes
    - cd wp-extend.wiki
    - git add .
    - |
      if ! git diff --quiet HEAD; then
        COMMIT_MSG="Update wiki pages from README.md files $(date +'%Y-%m-%d')"
        echo "$COMMIT_MSG"
        git commit -m "$COMMIT_MSG"
        git push
      else
        echo "No changes to the wiki, skipping commit and push."
    - echo "Wiki update process completed successfully."