stages:
  - mirror

mirror_repository_to_github:
  stage: mirror
  tags:
    - gitlab.motivar.io
  image: alpine/git
  only:
    - main
  script:
    # Configure Git with your details
    - git config --global user.name "ngiannopoulos"
    - git config --global user.email "gnnpls.nikos@gmail.com"

    # Add GitHub as a remote. Use a unique name to avoid conflicts.
    - git remote add github-mirror https://github.com/Motivar/wp-extend.git

    # Use the CI/CD token or personal access token for authentication
    - git push --mirror https://${GH_TOKEN}@github.com/Motivar/wp-extend.git

  # Optional: Clean up by removing the temporary remote to avoid conflicts in future runs.
  after_script:
    - git remote remove github-mirror
