<?php

if (!defined('ABSPATH')) {
    exit;
}

/**
 * EWP REST Health — OpenAPI 3.0 Spec Generator
 *
 * Converts WordPress REST route metadata into a minimal OpenAPI 3.0
 * specification for rendering in Swagger UI.
 *
 * Intentionally limited scope: paths, parameters, requestBody,
 * basic responses, nonce security scheme.
 * Previous successful test params (from history) are injected as
 * 'example' values so Swagger UI forms are pre-filled.
 *
 * @package EWP\RestHealth
 * @since   1.0.0
 */
class EWP_REST_Health_OpenAPI
{
    /** @var EWP_REST_Health_Runner */
    private $runner;

    public function __construct(EWP_REST_Health_Runner $runner)
    {
        $this->runner = $runner;
    }

    // -------------------------------------------------------------------------
    // Public API
    // -------------------------------------------------------------------------

    /**
     * Generate the complete OpenAPI 3.0 spec array.
     *
     * @param  array[]  $routes         Route metadata from Discovery::get_routes_for_plugins()
     * @param  int      $user_id        Current user ID (for history-based examples)
     * @param  string[] $method_filter  If non-empty, only include these HTTP methods (uppercase)
     * @return array                    OpenAPI 3.0 structure (json_encode-ready)
     */
    public function generate(array $routes, int $user_id, array $method_filter = []): array
    {
        $paths = [];

        foreach ($routes as $meta) {
            $open_path = $this->normalize_route_to_path($meta['route']);
            if (!isset($paths[$open_path])) {
                $paths[$open_path] = [];
            }
            $paths[$open_path] = array_merge(
                $paths[$open_path],
                $this->build_path_item($meta, $user_id, $method_filter)
            );
        }

        return [
            'openapi' => '3.0.0',
            'info'    => [
                'title'       => get_bloginfo('name') . ' REST API',
                'version'     => '1.0.0',
                'description' => 'Generated by EWP REST Health. Super-admin only.',
            ],
            'servers' => [
                ['url' => rest_url(), 'description' => 'WordPress REST API'],
            ],
            'paths'      => $paths ?: new stdClass(), // empty object, not array
            'components' => [
                'securitySchemes' => [
                    'WPNonce' => [
                        'type'        => 'apiKey',
                        'in'          => 'header',
                        'name'        => 'X-WP-Nonce',
                        'description' => 'WordPress REST nonce (wp_create_nonce("wp_rest")).',
                    ],
                ],
            ],
            'security' => [['WPNonce' => []]],
        ];
    }

    // -------------------------------------------------------------------------
    // Private helpers
    // -------------------------------------------------------------------------

    /**
     * Build an OpenAPI path item (all HTTP methods for one route).
     *
     * @param  string[] $method_filter  If non-empty, skip methods not in this list.
     */
    private function build_path_item(array $meta, int $user_id, array $method_filter = []): array
    {
        $item        = [];
        $url_params  = $meta['url_params'] ?? [];
        $args        = $meta['args'] ?? [];

        // Shared path parameters
        $path_params = [];
        foreach ($url_params as $param_name) {
            $path_params[] = [
                'name'     => $param_name,
                'in'       => 'path',
                'required' => true,
                'schema'   => ['type' => 'string'],
            ];
        }

        foreach ($meta['methods'] as $method) {
            if (!empty($method_filter) && !in_array($method, $method_filter, true)) {
                continue;
            }
            $http_method  = strtolower($method);
            $last_example = $this->get_last_success($meta['route'], $method, $user_id);
            $operation    = $this->build_operation($meta, $method, $args, $path_params, $last_example);
            $item[$http_method] = $operation;
        }

        return $item;
    }

    private function build_operation(array $meta, string $method, array $args, array $path_params, array $last_example): array
    {
        $operation = [
            'summary'   => $method . ' ' . ($meta['route'] ?? ''),
            'tags'      => [$meta['namespace'] ?? 'other'],
            'security'  => [['WPNonce' => []]],
            'responses' => [
                '200' => ['description' => 'Success'],
                '403' => ['description' => 'Forbidden'],
                '404' => ['description' => 'Not Found'],
            ],
        ];

        // Description: permission callback + controller + handler
        $cb = $meta['permission_callback'] ?? [];
        if (!empty($cb['name'])) {
            $cb_label = $cb['valid'] ? '✓' : '⚠ not callable';
            $parts    = ['Permission: `' . $cb['name'] . '` ' . $cb_label];
            if (!empty($meta['controller_class'])) {
                $parts[] = 'Controller: `' . $meta['controller_class'] . '`';
            }
            if (!empty($meta['callback_name'])) {
                $parts[] = 'Callback: `' . $meta['callback_name'] . '`';
            }
            $operation['description'] = implode(' | ', $parts);
        }

        // Parameters
        $parameters = $path_params;

        if (!empty($args)) {
            if (in_array(strtolower($method), ['get', 'head', 'delete'], true)) {
                foreach ($args as $arg_name => $arg) {
                    $param = [
                        'name'   => $arg_name,
                        'in'     => 'query',
                        'schema' => $this->map_arg_to_schema($arg),
                    ];
                    if (!empty($arg['description'])) {
                        $param['description'] = $arg['description'];
                    }
                    if (!empty($arg['required'])) {
                        $param['required'] = true;
                    }
                    if (isset($last_example[$arg_name])) {
                        $param['example'] = $last_example[$arg_name];
                    }
                    $parameters[] = $param;
                }
            } else {
                // POST / PUT / PATCH — requestBody
                $properties = [];
                $required   = [];

                foreach ($args as $arg_name => $arg) {
                    $schema = $this->map_arg_to_schema($arg);
                    if (isset($last_example[$arg_name])) {
                        $schema['example'] = $last_example[$arg_name];
                    }
                    $properties[$arg_name] = $schema;
                    if (!empty($arg['required'])) {
                        $required[] = $arg_name;
                    }
                }

                $body_schema = ['type' => 'object', 'properties' => $properties];
                if (!empty($required)) {
                    $body_schema['required'] = $required;
                }
                if (!empty($last_example)) {
                    $body_schema['example'] = $last_example;
                }

                $operation['requestBody'] = [
                    'content' => ['application/json' => ['schema' => $body_schema]],
                ];
            }
        }

        if (!empty($parameters)) {
            $operation['parameters'] = $parameters;
        }

        return $operation;
    }

    /**
     * Map a WP REST arg definition to an OpenAPI schema object.
     */
    private function map_arg_to_schema(array $arg): array
    {
        $wp_type  = $arg['type'] ?? 'string';
        $wp_type  = is_array($wp_type) ? $wp_type[0] : $wp_type;
        $type_map = [
            'string'  => 'string',
            'integer' => 'integer',
            'number'  => 'number',
            'boolean' => 'boolean',
            'array'   => 'array',
            'object'  => 'object',
        ];

        $schema = ['type' => $type_map[$wp_type] ?? 'string'];

        if (!empty($arg['description'])) {
            $schema['description'] = $arg['description'];
        }
        if (isset($arg['default'])) {
            $schema['default'] = $arg['default'];
        }
        if (!empty($arg['enum'])) {
            $schema['enum'] = array_values((array) $arg['enum']);
        }
        if (isset($arg['minimum'])) {
            $schema['minimum'] = $arg['minimum'];
        }
        if (isset($arg['maximum'])) {
            $schema['maximum'] = $arg['maximum'];
        }
        if ($schema['type'] === 'array' && !empty($arg['items'])) {
            $schema['items'] = $this->map_arg_to_schema((array) $arg['items']);
        }

        return $schema;
    }

    /**
     * Convert a WP REST route pattern to an OpenAPI path string.
     *
     * /filox/v1/booking/(?P<id>\d+) → /filox/v1/booking/{id}
     */
    private function normalize_route_to_path(string $route): string
    {
        return preg_replace('/\(\?P<([^>]+)>[^)]+\)/', '{$1}', $route);
    }

    /**
     * Get params from the most recent successful test for this route+method.
     *
     * @return array  Params from last 2xx history entry, or [].
     */
    private function get_last_success(string $route, string $method, int $user_id): array
    {
        if ($user_id <= 0) {
            return [];
        }
        foreach ($this->runner->get_history($route, $method, $user_id) as $entry) {
            $status = $entry['status'] ?? 0;
            if ($status >= 200 && $status < 300) {
                return $entry['params'] ?? [];
            }
        }
        return [];
    }
}
