name: Publish Plugin Package

on:
  push:
    branches:
      - main  # Adjust this as necessary

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'  # Match your PHP version

      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Specify Node.js version
          registry-url: 'https://npm.pkg.github.com'

      - name: Install Composer dependencies
        run: composer install --no-dev --no-progress --prefer-dist --no-suggest --optimize-autoloader --ignore-platform-reqs

      - name: Build Plugin
        run: |
          npm install
          npm run build
          composer update -o
          find . -type d -name '.git' | xargs rm -rf
          zip -r wp-extend.zip .  # Customize your build steps as needed

      - name: Generate Tag
        id: tagger
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch  # Sets the default version bump. Can be overridden by commit messages. Options are major, minor, patch.
          RELEASE_BRANCHES: main  # Only create a release/tag when on this branch
          TAG_PREFIX: "v"  # Prefix for the tag, resulting in tags like v1.0.0

      - name: Create Release
        if: steps.tagger.outputs.new_tag != ''  # Only runs if a new tag was created
        uses: softprops/action-gh-release@v1
        with:
          files: wp-extend.zip
          tag_name: ${{ steps.tagger.outputs.new_tag }}
          token: ${{ secrets.GITHUB_TOKEN }}
